name: CI

on:
  push:
    branches:
      - '1.5'
      - '1.6'
      - '1.7'
      - '1.8'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build all docker images
        env:
          MAILU_VERSION: ${{ env.BRANCH }}
        run: docker-compose -f tests/build.yml build
      - name: Push images
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/admin ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/clamav ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/docs ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dovecot ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/fetchmail ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nginx ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/none ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/postfix ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/postgresql ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/radicale ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/rainloop ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/roundcube ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/rspamd ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/setup ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/traefik-certdumper ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/unbound